"""Platform catalogue for the Knowledge Kernel ecosystem.

This is the canonical registry of every platform-aware integration
the project supports. It serves three distinct purposes, all
derived from one source of truth:

  1. **Architectural enforcement** — boundary tests use it to
     detect platform dependencies leaking into consumers/.
  2. **Documentation generation** — tooling can list supported
     platforms and their canonical locations from this file.
  3. **Scaffolding** — a new platform adapter can be generated by
     reading this registry and creating the corresponding entry
     under integrations/.

A new platform adapter MUST add an entry here on the same commit
that creates the integration directory. Removing a platform
removes the entry. The two operations are inseparable.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterator


@dataclass(frozen=True)
class PlatformBoundary:
    """A platform-aware package and its canonical location.

    Attributes:
        package:     Top-level Python module name consumers/ must
                     NOT import (e.g. ``hermes``).
        location:    Path under the repo root where the platform
                     adapter lives (e.g. ``integrations/hermes``).
        description: One-line description for documentation.
        status:      ``active`` for an existing integration,
                     ``future`` for a planned one.
    """
    package: str
    location: str
    description: str
    status: str = "active"  # or "future"


# ---------------------------------------------------------------------------
# The catalogue
# ---------------------------------------------------------------------------
# A platform is "active" once integrations/<location>/ exists. Until then
# it is "future" and tooling may or may not scaffold it.

PLATFORM_BOUNDARIES: tuple[PlatformBoundary, ...] = (
    PlatformBoundary(
        package="hermes",
        location="integrations/hermes",
        description="Hermes Agent integration (skills, tools, scripts).",
        status="active",
    ),
    PlatformBoundary(
        package="openclaw",
        location="integrations/openclaw",
        description="OpenClaw agent framework integration.",
        status="future",
    ),
    PlatformBoundary(
        package="zeroclaw",
        location="integrations/zeroclaw",
        description="ZeroClaw agent framework integration.",
        status="future",
    ),
    PlatformBoundary(
        package="cursor",
        location="integrations/cursor",
        description="Cursor IDE integration.",
        status="future",
    ),
    PlatformBoundary(
        package="claude",
        location="integrations/claude",
        description="Anthropic Claude integration.",
        status="future",
    ),
    PlatformBoundary(
        package="langgraph",
        location="integrations/langgraph",
        description="LangGraph framework integration.",
        status="future",
    ),
    PlatformBoundary(
        package="autogen",
        location="integrations/autogen",
        description="AutoGen framework integration.",
        status="future",
    ),
    PlatformBoundary(
        package="crewai",
        location="integrations/crewai",
        description="CrewAI framework integration.",
        status="future",
    ),
)


# ---------------------------------------------------------------------------
# Helpers — read-only access
# ---------------------------------------------------------------------------

def by_package(name: str) -> PlatformBoundary | None:
    """Return the platform entry for a top-level package name."""
    for p in PLATFORM_BOUNDARIES:
        if p.package == name:
            return p
    return None


def active() -> Iterator[PlatformBoundary]:
    """Yield only the platforms with an ``active`` status."""
    return (p for p in PLATFORM_BOUNDARIES if p.status == "active")


def packages() -> frozenset[str]:
    """Set of all package names (active and future)."""
    return frozenset(p.package for p in PLATFORM_BOUNDARIES)


def locations() -> frozenset[str]:
    """Set of all canonical locations."""
    return frozenset(p.location for p in PLATFORM_BOUNDARIES)
